services:
  webhook:
    build:
      context: ./webhook
    ports:
      - 3000:3000
    depends_on:
      - mongo
  log:
    build:
      context: ./crn
      ports:
        - 31337:31337
      depends_on:
        - mongo
  mongo:
    image: mongo:4.4.18
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: 'false'
  nginx:
    container_name: proxy_nginx
    depends_on:
      - webhook
      - mongo
      - log
    image: nginx:latest
    ports:
      - '80:80'
    env_file:
      - .env
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./xxe:/var/www/xxe
    restart: always

volumes:
  mongo_data: