services:
  webhook:
    build:
      context: ./webhook
    ports:
      - 3000:3000
    env_file: .env
  # db:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - ./db_data:/docker-entrypoint-initdb.d
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - 5432:5432
  #   healthcheck:
  #     test: [ "CMD", "pg_isready", "-U", "${DB_USER}" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  mongo:
    image: mongo:4.2.3-bionic
    container_name: my-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=requests
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminqwe
    # volumes:
    #   # seeding scripts
    #   - ./mongo-entrypoint:/docker-entrypoint-initdb.d
    #   - mongodb:/data/db
    #   - mongoconfig:/data/configdb
  nginx:
    container_name: proxy_nginx
    depends_on:
      - webhook
      - mongo
    image: nginx:latest
    ports:
      - '80:80'
    env_file:
      - .env
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always

